### ISSUE TITLE
PromoteSubscribers in a Control-flow stage stopped working

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1196]
# Description

The promote subcribers on a control flow stage doesn't work anymore. We used to be able to promote subscribers anything that a Control Flow stage subscribed to, which had got verified in the control-flow's upstream. However, the promote subscribers button no longer functions:

# Screenshots

https://github.com/akuity/kargo/assets/12677113/4f154dba-87fd-46b3-9d68-7fdf656f8796

# Steps to Reproduce

# Version

```
Paste the output from `kargo version` here.
```

# Logs

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
I confirmed this seems to be an UI issue:

```
$ kargo stage promote-subscribers --freight 954d803b5277248f39c2f27e6d7124f103971186 kargo-guestbook prod-us
Promotion Created: "prod-use1.01hgh0je9eefcst0b4xn91w4am.954d803"
Promotion Created: "prod-usw1.01hgh0jeb5vw32qd0sgfnpawzy.954d803"
Promotion Created: "prod-usw2.01hgh0jecgb33qczskhwkqv40b.954d803"
```

**Comment by rbreeze** [comment]
Fixed by #1200

**Comment by jessesuen** [comment]
Reopening because this still isn't doing what it is supposed to.

PromoteSubscribers is supposed to call the promote subscribers API to promote N downstream stages simultaneously. But the UI still makes me click a single Stage to promote:

https://github.com/akuity/kargo/assets/12677113/924b2a19-9d8f-4c37-b7fd-1f6f1ea7356b

**Comment by jessesuen** [comment]
It seems to be that promotion was failing not due to UI problem. Closing
