### ISSUE TITLE
After Update to 1.5.2, Kargo Promotions all Pending Indefinitely

### ISSUE THREAD

**Issue by avo-sepp** [akuity/kargo#4383]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

Kargo Stage Promotions sit idle. In Pending state. 

This might be related to our earlier issue where we updated to a middle-ground version. We're going to attempt a rollback and roll-forward in the meantime. I did make sure that all Kargo components pulled the latest image. But if there is insight into how to fix this live it would be greatly appreciated. 🙏🏻 

# Version

```
1.5.2
```

# Logs

### Kargo-Controller Log

```
time="2025-06-12T19:57:10Z" level=error msg="failed to update Stage status after syncing Promotions" controlFlow=false error="Stage.kargo.akuity.io \"<redacted>" is invalid: [status.freightHistory[0].verificationHistory[0].id: Required value, status.freightHistory[1].verificationHistory[0].id: Required value, <nil>: Invalid value: \"null\": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]" namespace=<redacted> stage=<redacted>
```
### Kargo-API Log
```
time="2025-06-12T20:07:52Z" level=info msg="finished unary call" connect.duration=47.622944ms connect.method=GetPromotion connect.service=akuity.io.kargo.service.v1alpha1.KargoService connect.start_time="2025-06-12T20:07:52Z"
time="2025-06-12T20:08:38Z" level=error msg="finished streaming call" connect.code=internal connect.duration=1m0.000721403s connect.method=WatchFreight connect.service=akuity.io.kargo.service.v1alpha1.KargoService connect.start_time="2025-06-12T20:07:38Z" error="internal: context canceled"
time="2025-06-12T20:08:38Z" level=error msg="finished streaming call" connect.code=internal connect.duration=59.999789792s connect.method=WatchStages connect.service=akuity.io.kargo.service.v1alpha1.KargoService connect.start_time="2025-06-12T20:07:38Z" error="internal: context canceled"
time="2025-06-12T20:08:52Z" level=error msg="finished streaming call" connect.code=internal connect.duration=1m0.000194396s connect.method=WatchPromotion connect.service=akuity.io.kargo.service.v1alpha1.KargoService connect.start_time="2025-06-12T20:07:52Z" error="internal: context canceled"
time="2025-06-12T20:09:24Z" level=error msg="finished streaming call" connect.code=internal connect.duration=1m46.149698717s connect.method=WatchWarehouses connect.service=akuity.io.kargo.service.v1alpha1.KargoService connect.start_time="2025-06-12T20:07:38Z" error="internal: context canceled"
```

**Comment by avosepp** [comment]
Confirmed the issue is not present in 1.5.1, rollback got the promotion going again. 

Then I rolled forward to 1.5.2 and ran into the same issue. Promotion is stuck in pending state. 
Will Rollback to 1.5.1 until I hear back from the team.

**Comment by krancour** [comment]
#4271 and #4310 look like the only things that could be related to this. I'll research.

cc @hiddeco in case of any insight.

**Comment by krancour** [comment]
Oh...

@avo-sepp roll back your CRDs to v1.5.1. That would not have happened automatically.

**Comment by krancour** [comment]
Err... or the (correct) v1.5.2 CRDs.

I think you have (stricter) CRDs from the botched v1.5.2 release (`main`) that are choking on something the 1.5.1 and (correct) 1.5.2 controllers were doing incorrectly.

i.e. We fixed a bug (meant for 1.6) where a particular status field wasn't set and added a validation (we don't usually do validation on status) to prevent a regression.

But the mis-match of CRD and controllers is probably the culprit here.

**Comment by avosepp** [comment]
I believe I have the correct CRDs in place. ArgoCD did see a OutOfSync for `promotions` and `stages`, but I still have the issue of pending promotions. Do you have a tell I can look for to see if I'm on the wrong CRD?

**Comment by avosepp** [comment]
![Image](https://github.com/user-attachments/assets/5d32d8d3-e302-4055-ad52-db69294226b1)

ArgoCD seems to be handling CRD changes with the versions just fine. It's out of sync here but when I move between 1.5.1 and 1.5.2 it syncs the CRDs to match what I'm getting from the Helm chart.

**Comment by krancour** [comment]
Thanks @avo-sepp. @hiddeco thinks he's found the issue. Standby.

**Comment by hiddeco** [comment]
@avo-sepp sorry about this, I expect [`v1.5.3`](https://github.com/akuity/kargo/releases/tag/v1.5.3) to bring you more joy.

**Comment by avosepp** [comment]
![Image](https://github.com/user-attachments/assets/d282a195-0f6c-47f4-9e93-aec0f164776c)

`1.5.3` did spark joy. Thank you both!
